### ISSUE TITLE
LLM on Xeon by vLLM + Ray

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#194]
LLM on Xeon by vLLM + Ray

**Comment by Jian-Zhang** [comment]
For this item, we should breakdown it. LLM on Xeon/Gaudi with vLLM; Ray-Serve, and vLLM-on-Ray ==> it is three serving backends. Same for Gaudi.  

vLLM -  done for both Xeon and Gaudi. https://github.com/opea-project/GenAIComps/pull/5; https://github.com/opea-project/GenAIComps/pull/126
Ray-Serve - https://github.com/opea-project/GenAIComps/pull/104
vLLM-on-Ray - WIP.
