### ISSUE TITLE
MI6 User Feedback Management

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#196]
MI6 User Feedback Management

**Comment by kevinintel** [comment]
wait for 
https://github.com/opea-project/GenAIExamples/issues/270

**Comment by hteeyeoh** [comment]
Since the implementation of feedback management component already merged into main. Shall we close this issue?

**Comment by hteeyeoh** [comment]
This have been implemented in [PR581](https://github.com/opea-project/GenAIComps/pull/581) and already merged into main.
Hence, closing this issue.
