### ISSUE TITLE
Prompting

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#198]
Prompting

**Comment by hteeyeoh** [comment]
Hi @kevinintel , @feng-intel ,
Is this ticket refer to the prompt registry components? If yes, that we have already implemented in GenAIcomps and in our ProductivitySuite example. If not, can you please provide details on this ticket?

**Comment by kevinintel** [comment]
yes, prompt registry
please link pr and close this issue

**Comment by hteeyeoh** [comment]
Sure. Thanks @kevinintel .

**Comment by hteeyeoh** [comment]
> yes, prompt registry please link pr or paste the url and close this issue

Prompt Registry components have been implemented in this [PR294](https://github.com/opea-project/GenAIComps/pull/294)
This is merged and available in [main](https://github.com/opea-project/GenAIComps/tree/main/comps/prompt_registry/mongo)
