### ISSUE TITLE
OneClickOPEA on 3 or more examples

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#263]

**Comment by daisy-ycguo** [comment]
Added and/or updated 4 GenAIExamples (DocSum, CodeTrans, CodeGen, ChatQnA) kubernetes manifests:
- [Add Kubernetes manifest files for deploying DocSum](https://github.com/opea-project/GenAIExamples/pull/434)
- [Add Kubernetes manifest files for deploying CodeTrans](https://github.com/opea-project/GenAIExamples/pull/435)
- [Update Kubernetes manifest files for CodeGen](https://github.com/opea-project/GenAIExamples/pull/441)
- [Update Kubernetes manifest files for deploying ChatQnA](https://github.com/opea-project/GenAIExamples/pull/445)

**Comment by daisy-ycguo** [comment]
Upgraded 2 existing examples, added two new examples. Done.
