### ISSUE TITLE
TEI not working on gaudi GPU

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIComps#281]
the repo https://github.com/huggingface/tei-gaudi

does not work, I see the documents only show CPU support, but I would like a feature request to enable the GPU parts, so that I can integrate it into microsoft graphrag.

**Comment by eero-t** [comment]
Which HW you're trying to use?   Gaudi is not a GPU, but AI accelerator...

**Comment by endomorphosis** [comment]
Im using a Gaudi2 system with 8 accelerators (i reflexively used the term GPU)

**Comment by eduand-alvarez** [comment]
can you try the code in this sample to see if it works for you? https://github.com/HabanaAI/Gaudi-tutorials/blob/main/PyTorch/RAG_Application/RAG-on-Intel-Gaudi.ipynb

**Comment by endomorphosis** [comment]
yes, i have already done so, that has the faulty repository

!git clone https://github.com/huggingface/tei-gaudi

**Comment by louie-tsai** [comment]
> the repo https://github.com/huggingface/tei-gaudi
> 
> does not work, I see the documents only show CPU support, but I would like a feature request to enable the GPU parts, so that I can integrate it into microsoft graphrag.

Could you explain more what doesn't work for you in  https://github.com/huggingface/tei-gaudi?
Once you launch the local tei-gaudi service, do you get correct output from your curl request?
![image](https://github.com/user-attachments/assets/ba0ce0a8-f46e-4ebf-bbb7-a618341a7f21)

**Comment by endomorphosis** [comment]
I have seen that the repository has been updated since i posted this ticket, and it is now working and stable with the migration from v1.2.2 to v1.4.0 see e.g. https://github.com/huggingface/tei-gaudi/commit/3db17966712cd17ef48b0e09e1778523239106da
