### ISSUE TITLE
datapre-redis: too much hard coded listening port 

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIComps#282]
The Currently datapre-redis microservice uses the 3 different hard coded tcp ports(6007, 6008, 6009) for different purpose:

- Upload file:  http://x.y.z:6007/v1/dataprep
- Get file:        http://x.y.z:6008/v1/dataprep/get_file
- Delete file:   http://x.y.z.:6009/v1/dataprep/delete_file

This seems not the normal way to define industry standard RESTful API. We would suggest:

1. Bind one listening port (i.e. 6007) for this microservice, and use different URL for different purpose

3. Make the listening port configurable through environment variable, just like other microservices in GenAIComps.

**Comment by ftian1** [comment]
agree your comment. we will fix it asap

**Comment by kevinintel** [comment]
1. WIP
2. Even you set the port from env, if you don't set it before docker compose, it still can't work. We need to discuss it, but put th ports in one document is not bad because you can find all ports.

**Comment by zhlsunshine** [comment]
Hi @ftian1 and @kevinintel, before you work on this, I also open an issue for this dataprep-redis REST API definition here: https://github.com/opea-project/GenAIComps/issues/394. We may not need extra API for this microservice, just follow the [best practice](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design#define-api-operations-in-terms-of-http-methods)

**Comment by lianhao** [comment]
@lkk12014402  is PR #424 meant to resolve this issue? If so, I think this can be marked as completed

**Comment by lkk12014402** [comment]
> @lkk12014402 is PR #424 meant to resolve this issue? If so, I think this can be marked as completed

yes, the pr fixed this issue.
