### ISSUE TITLE
add huggingface TEI Support with intel max GPU

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIComps#306]
Rahul from Intel liftoff provided me with some code with support for intel GPU max, that he wanted some of the college students to use to process embeddings, I told him that I wanted the college students to design against the OPEA reference standard, and I asked him whether this was implemented inside of huggingface Text Embedding Interface TEI. He was unsure whether or not this was implemented, and so therefore, I am raising a feature request here and adding his code.

https://gist.github.com/rahulunair/5e048b76518962eddeeafaf9bcf8da1b

![image](https://github.com/user-attachments/assets/6c7de279-83f1-42a3-8c56-f5886dfcd6d8)

**Comment by ZailiWang** [comment]
Hi @endomorphosis , currently the support for Max GPU is not prioritized.
