### ISSUE TITLE
doc: empty README.md files need content

### ISSUE THREAD

**Issue by dbkinder** [opea-project/GenAIComps#315]
These README "documents" are empty and need some content:

./comps/guardrails/langchain/README.md
./comps/cores/mega/README.md
./comps/vectorstores/langchain/chroma/README.md
./comps/llms/summarization/tgi/README.md
./comps/knowledgegraphs/langchain/README.md

**Comment by kevinintel** [comment]
we will request module owner to fill in

**Comment by WenjiaoYue** [comment]
Liang is the module owner and will help complete these README files. @lvliang-intel

**Comment by chickenrae** [comment]
> Liang is the module owner and will help complete these README files. @lvliang-intel

@lvliang-intel Can I help in anyway?

**Comment by letonghan** [comment]
Hi @dbkinder , after check, all of these READMEs are filled with proper contents. So this issue will be closed.
