### ISSUE TITLE
DockerFile.CPU 

### ISSUE THREAD

**Issue by preethivenkatesh** [opea-project/GenAIComps#336]
```docker run -it --name vllm_service -p 8008:80 -e HF_TOKEN=${HUGGINGFACEHUB_API_TOKEN} -v ./data:/data vllm:cpu /bin/bash -c "cd / && export VLLM_CPU_KVCACHE_SPACE=40 && python3 -m vllm.entrypoints.openai.api_server --model ${your_hf_llm_model} --port 80"```
causes the below issue, since the vllm:cpu image entry point is set to `ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]`
```
api_server.py: error: unrecognized arguments: /bin/bash -c cd / && export VLLM_CPU_KVCACHE_SPACE=40 && python3 -m vllm.entrypoints.openai.api_server --model  --port 80
```
one of the options is to fix the issue by passing the `--entrypoint` to fix the issue in readme

```docker run --entrypoint /bin/bash -it --name vllm_service -p 8008:80 -e HF_TOKEN=${HUGGINGFACEHUB_API_TOKEN} -v ./data:/data vllm:cpu -c "cd / && export VLLM_CPU_KVCACHE_SPACE=40 && python3 -m vllm.entrypoints.openai.api_server --model Intel/neural-chat-7b-v3-3 --port 80"```

**Comment by stevegrubb** [comment]
I think this can be closed as the launch script now uses '-e' to inject environmental models.
