### ISSUE TITLE
GraphRAG

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#355]

**Comment by endomorphosis** [comment]
I am interested in this as well. keep me in the loop on the tasks that need to be done. Right now I am trying to get llama 3.1 405B 8bit running on Gaudi-TGI, and llama 3.1 405B GGUF with speculative decoding using llama 3.1 8B working on Xeon

**Comment by XuhuiRen** [comment]
enabled langchain and llamaindex two versions
