### ISSUE TITLE
Redis connection is not consistent in redis dataprep

### ISSUE THREAD

**Issue by bjzhjing** [opea-project/GenAIComps#358]
There are both 'from langchain_community.vectorstores import Redis' and 'import redis' defined in prepare_doc_redis.py. Redis.from_texts_return_keys() is with REDIS_URL as connection, while redis.Redis() takes the combination of REDIS_HOST and REDIS_PORT as connection. When the former and the latter are not the same, it gets failed to get data from vector database.

**Comment by preethivenkatesh** [comment]
Please check if the PR fixes it

**Comment by wangkl2** [comment]
Verified it works with this merged PR on my side. Close it. Thanks.
