### ISSUE TITLE
OOlama failure 

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIComps#367]
[2024-07-30 09:27:57,632] [    INFO] - CORS is enabled.
[2024-07-30 09:27:57,633] [    INFO] - Setting up HTTP server
[2024-07-30 09:27:57,633] [    INFO] - Uvicorn server setup on port 9000
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
[2024-07-30 09:27:57,650] [    INFO] - HTTP server setup successful
INFO:     127.0.0.1:52782 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f2a36fce2d0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
  |     raise exc
  |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
  |     await self.app(scope, receive, send_wrapper)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 258, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    |     return await self._loop.create_connection(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    |     raise exceptions[0]
    |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    |     sock = await self._connect_sock(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    |     await self.sock_connect(sock, address)
    |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    |     return await fut
    |            ^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    |     raise OSError(err, f'Connect call failed {address}')
    | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/user/comps/llms/text-generation/ollama/llm.py", line 36, in stream_generator
    |     async for text in ollama.astream(input.query):
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 520, in astream
    |     raise e
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 503, in astream
    |     async for chunk in self._astream(
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 488, in _astream
    |     async for stream_resp in self._acreate_generate_stream(prompt, stop, **kwargs):
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 187, in _acreate_generate_stream
    |     async for item in self._acreate_stream(
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 294, in _acreate_stream
    |     async with session.post(
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    |     self._resp = await self._coro
    |                  ^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    |     conn = await self._connector.connect(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    |     proto = await self._create_connection(req, traces, timeout)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    |     _, proto = await self._create_direct_connection(req, traces, timeout)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    |     raise last_exc
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    |     transp, proto = await self._wrap_create_connection(
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    |     raise client_error(req.connection_key, exc) from exc
    | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
    +------------------------------------

**Comment by endomorphosis** [comment]
Failure occured within the context of the docker example provided.

**Comment by wangkl2** [comment]
@endomorphosis Thanks for reporting the issues. I can reproduce the issue you met on my side for the `ollama/llama3` example. 
![image](https://github.com/user-attachments/assets/9f215f0a-e197-4a17-be5c-9b2b482e3f26)


From `INFO: 127.0.0.1:52782 - "POST /v1/chat/completions HTTP/1.1" 200 OK`, the 9000 port is able to be access and the request is successfully sent. 

But from the output of `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]`, the microservice launched by the docker container cannot get access to the 11434 port of the ollama endpoint, which should be outside of the docker container. 

The solution is to follow https://github.com/opea-project/GenAIComps/tree/main/comps/llms/text-generation/ollama#run-the-ollama-microservice to use `--network host` while launching the microservice. This will help map the ollama 11434 port on bare metal to the docker container. 

Desired output after fixing:
![image](https://github.com/user-attachments/assets/18f2a7b8-9307-4afc-a3bd-ec54f301b29d)

**Comment by wangkl2** [comment]
@endomorphosis May I ask whether adding `--network host` flag solves your issue now?

**Comment by endomorphosis** [comment]
I will check this this weekend

**Comment by endomorphosis** [comment]
```
docker run --network host opea/llm-ollama:latest
```
it starts correctly, but running 

```
curl http://127.0.0.1:9000/v1/chat/completions  -X POST   -d '{"model": "llama3", "query":"What is Deep Learning?","max_new_tokens":32,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":true}'   -H 'Content-Type: application/json'
```
results
```
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    |     await self.sock_connect(sock, address)
    |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    |     return await fut
    |            ^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    |     raise OSError(err, f'Connect call failed {address}')
    | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/user/comps/llms/text-generation/ollama/llm.py", line 36, in stream_generator
    |     async for text in ollama.astream(input.query):
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 520, in astream
    |     raise e
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 503, in astream
    |     async for chunk in self._astream(
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 488, in _astream
    |     async for stream_resp in self._acreate_generate_stream(prompt, stop, **kwargs):
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 187, in _acreate_generate_stream
    |     async for item in self._acreate_stream(
    |   File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 294, in _acreate_stream
    |     async with session.post(
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    |     self._resp = await self._coro
    |                  ^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    |     conn = await self._connector.connect(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    |     proto = await self._create_connection(req, traces, timeout)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    |     _, proto = await self._create_direct_connection(req, traces, timeout)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    |     raise last_exc
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    |     transp, proto = await self._wrap_create_connection(
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    |     raise client_error(req.connection_key, exc) from exc
    | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
    +------------------------------------
```

**Comment by wangkl2** [comment]
@endomorphosis 

From your log, the `11434` port still cannot be connected for your ollama microservice from the docker container. Since you've set `--network host`, all ports (including `9000 and 11434`, which would be used in this example) should be mapped between bare metal and the docker container. The reason why you still meet this issue is might due to 11434 port is not even activated and listened by the ollama service. 

To confirm if this is the reason and fix it, please do the following:
* Step1: Check whether 11434 port is activate on bare metal:
```
sudo apt install net-tools
sudo netstat -tunlp
```
The desired output should be the following: (both 9000 and 11434 should be active)
![image](https://github.com/user-attachments/assets/378f1a53-1457-439b-a2f9-4e1099cda78e)

* Step2: If there is no `127.0.0.1:11434` in the output of Step1, check whether ollama service is `active (running)` via:
```
sudo systemctl status ollama
```
The desired output should be:
![image](https://github.com/user-attachments/assets/9fa63d88-be28-40a7-9ae3-acf2c69680c7)

* Step3: If the ollama service is not active as in Step2, please setup ollama and pull the llama3 model following https://github.com/opea-project/GenAIComps/tree/main/comps/llms/text-generation/ollama#setup, as the requirement to run the opea ollama microservices. 

* Step4: Make sure the ollama service activate on bare metal, 11434 port is listened, and then rerun `curl http://127.0.0.1:9000/v1/chat/completions ...`

**Comment by wangkl2** [comment]
Does this fix your issue? Could you verify it on your side?

**Comment by wangkl2** [comment]
Solution provided. Close this issue due to inactivity.
