### ISSUE TITLE
llama 3.1 breaks on vllm and maybe on all other serving platforms

### ISSUE THREAD

**Issue by preethivenkatesh** [opea-project/GenAIComps#384]
llama 3.1 breaks on vllm with the error on --rope-scaling. The dockerfile.cpu needs to be updated to use the new IPEX patch and upgraded transformers if necessary. 
[https://github.com/vllm-project/vllm/issues/6689](https://github.com/vllm-project/vllm/issues/6689)

[https://download.pytorch.org/whl/nightly/cpu/torch-2.4.0.dev20240522%2Bcpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torch-2.4.0.dev20240522%2Bcpu-cp310-cp310-linux_x86_64.whl)
 
[https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_dev/cpu/intel_extension_for_pytorch-2.4.0%2Bgit55c342e-cp310-cp310-linux_x86_64.whl](https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_dev/cpu/intel_extension_for_pytorch-2.4.0%2Bgit55c342e-cp310-cp310-linux_x86_64.whl)

**Comment by preethivenkatesh** [comment]
I tried using the new IPEX and torch version in the `Dockerfile.cpu` but it  conflicts with the `requirements-cpu.txt` in vllm repo torchvision version.

**Comment by endomorphosis** [comment]
I looked into this today, there are two distinct issues to resolve

Upgrading transformers and accelerate fixed most of the problem with rope-scale in the huggingface libraries, and while updating huggingface and accelerate libraries will resolve this issue, the optimum library has a pending PR to fix its implementation of rope scale.

HPU and XPUs do not support fp8 inference, and thus llama-3.1 405B fp8 will not run on a single node, and moreover multi-node inference is not working with vllm, (i have not checked with other inference methods), so bf16 inference is limited to Xeon which performs at .5 t/s with fp8 and 1t/s with q_4 GGUF with oolama, but i haven't yet gotten speculative decoding working, i had some bug with regards to vocabulary size mismatch, which the may be an artefact of the fact that llama 3.1 has a new tokenizer for audio tokens.

**Comment by preethivenkatesh** [comment]
Thanks @endomorphosis. looks like from OPEA standpoint this will not run on HPU use cases? We'll have to breakdown all the potential issues exposed via OPEA. The issue I'm raising here from Xeon standpoint the OPEA GenAIComps must be updated the use the 0.5.3.post1 tag of vllm, and the dockerfile.cpu has to be updated with the new IPEX and torch patch as mentioned in the ticket.

**Comment by endomorphosis** [comment]
> Thanks @endomorphosis. looks like from OPEA standpoint this will not run on HPU use cases? We'll have to breakdown all the potential issues exposed via OPEA. The issue I'm raising here from Xeon standpoint the OPEA GenAIComps must be updated the use the 0.5.3.post1 tag of vllm, and the dockerfile.cpu has to be updated with the new IPEX and torch patch as mentioned in the ticket.

It will work on opea, you just need to give the optimum team a few days to fix the remaining bugs with the rope scale, and then I can make a pull request to gaudi-tgi and to vllm to bump versions. 

With regards to gaudi-405b, I was talking to a member of LAION named @nisten , and he used the gaudi docs to implement bitnet in fp8 by writing a new kernel, so perhaps he can assist with this.

![image](https://github.com/user-attachments/assets/bb44bf35-da77-4f42-b157-ef070744260c)

**Comment by preethivenkatesh** [comment]
@kevinintel @hshen14  can we please add this as a known issue in the release notes both for Xeon and Gaudi and that users may experience issues until all the changes are merged into respective repos?
https://github.com/opea-project/GenAIComps/releases/tag/v0.8

**Comment by endomorphosis** [comment]
@nisten was able to accomplish 7 tok/s with llama_cpp with batched inference on a dual sapphire rapids box. 

![image](https://github.com/user-attachments/assets/e59d6ebb-2862-43d5-898b-18c0032d45f0)

**Comment by nisten** [comment]
it goes up to 7.1  tps, aaand that's about it, also with both x64 and ARMs llama.cpp doesnt scale much above 64 cores, helps a bit with prompt processing but slows down after

**Comment by nisten** [comment]
Ah wait, this is a dual CPU box,  forgot, need to setup numa and/or blis with right config for that so they dont sahre each others cache otherwise it tanks performance

**Comment by kevinintel** [comment]
> @kevinintel @hshen14 can we please add this as a known issue in the release notes both for Xeon and Gaudi and that users may experience issues until all the changes are merged into respective repos? https://github.com/opea-project/GenAIComps/releases/tag/v0.8

I prefer to add known issues in v1.0, otherwise there are lots of issues

**Comment by nisten** [comment]
> llama 3.1 breaks on vllm with the error on --rope-scaling. The dockerfile.cpu needs to be updated to use the new IPEX patch and upgraded transformers if necessary. [vllm-project/vllm#6689](https://github.com/vllm-project/vllm/issues/6689)
> 
> https://download.pytorch.org/whl/nightly/cpu/torch-2.4.0.dev20240522%2Bcpu-cp310-cp310-linux_x86_64.whl
> 
> https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_dev/cpu/intel_extension_for_pytorch-2.4.0%2Bgit55c342e-cp310-cp310-linux_x86_64.whl

P.s. for python 3.11 i just got it installed in a really stupid way lol

`# Downloade the wheel
wget https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_dev/cpu/intel_extension_for_pytorch-2.4.0%2Bgit55c342e-cp310-cp310-linux_x86_64.whl

# Renamed it to 311 trick pip
mv intel_extension_for_pytorch-2.4.0+git55c342e-cp310-cp310-linux_x86_64.whl intel_extension_for_pytorch-2.4.0+git55c342e-cp311-cp311-linux_x86_64.whl

# And then it installed fine
pip install intel_extension_for_pytorch-2.4.0+git55c342e-cp311-cp311-linux_x86_64.whl --no-deps`

**Comment by preethivenkatesh** [comment]
Yes, that worked for me, tried a slightly tried a different hack. But mianly raised this issue, so users know that this is an open and doesn't work OOB on Xeon until the changes are merged. @kevinintel  please update the ticket/ let me know when the fix happens in OPEA

**Comment by endomorphosis** [comment]
The dependencies for optimum habana were merged in a pull request, however there are still outstanding bugs with relation to quantization, and synapse dependencies, so for the time being there is not a formal request, but I have updated my repository so that it builds, and is able to load llama 3.1 8 and 70b models, I have also pushed a container to docker called endomorphosis/tgi_gaudi for the time being until a formal release optimum gaudi release is ready, and thus a formal tgi-gaudi release is ready.

https://github.com/endomorphosis/tgi-gaudi/tree/endomorphosis/llama3.1_tokenizer
https://hub.docker.com/r/endomorphosis/tgi_gaudi
