### ISSUE TITLE
datapre-redis: REST API definition for datapre-redis microservice should follow the best practice

### ISSUE THREAD

**Issue by zhlsunshine** [opea-project/GenAIComps#394]
The Currently datapre-redis microservice uses the 3 REST API for:

1. Upload file: `/v1/dataprep`
2. Get file: `/v1/dataprep/get_file`
3. Delete file: `/v1/dataprep/delete_file`

And these 3 APIs have the same request method: `-X POST`.
Basically, REST API provides different request methods for different purpose, such as `-X POST` for submitting the information in form, `-X GET` for getting something, `-X DELETE` for deleting something and `-X PUT/PATCH` for updating something. Please refer to [define-api-operations-in-terms-of-http-methods](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design#define-api-operations-in-terms-of-http-methods) for more detail.
Therefor, the best practice for REST API is that there should be only one REST API `/v1/dataprep` with different request method for uploading, getting and deleting files.

**Comment by lvliang-intel** [comment]
@zhlsunshine,
You are right. We are working for this.

**Comment by lvliang-intel** [comment]
It's fixed by #444.
