### ISSUE TITLE
Dependencies in speechT5 microservice is broken

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIComps#401]
root@laion-gaudi2-00:~/GenAIComps# docker run -p 7055:7055 --ipc=host -e http_proxy=$http_proxy -e https_proxy=$https_proxy opea/speecht5:latest
Traceback (most recent call last):
  File "/home/comps/tts/speecht5/speecht5_server.py", line 9, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

**Comment by sunnstix** [comment]
Most likely duplicate of https://github.com/opea-project/GenAIComps/issues/395?

**Comment by ctao456** [comment]
comment to take issue

**Comment by ctao456** [comment]
This was fixed as now the [tts requirements](https://github.com/opea-project/GenAIComps/blob/main/comps/tts/requirements.txt) includes `uvicorn`. Please pull from latest branch.
