### ISSUE TITLE
[Bug] LlamaIndex embeddings using wrong method

### ISSUE THREAD

**Issue by logan-markewich** [opea-project/GenAIComps#515]
The llamaindex tea embeddings are using a private method
https://github.com/opea-project/GenAIComps/blob/cd83854f93423a2327f07430fbf781e6f879ce41/comps/embeddings/llama_index/embedding_tei.py#L21

It's not clear to me if the embedding service is meant to handle query embeddings or document embeddings. But either way, we should be using `embed_model.get_text_embedding(text)` or `embed_model.get_query_embedding(query)`

Likely we should have two endpoints, one for query and one for normal text documents.

We might also want to consider using `get_text_embeddings_batch()` instead of processing one document at a time, but again, depends on how we want to define our embedding endpoints

**Comment by srinarayan-srikanthan** [comment]
the object is used to call the functions, but agree that we might want to consider text_embedding_batch()

**Comment by logan-markewich** [comment]
I've also noticed that the embeddings API in general only works by sending a single piece of text at a time. This is neither efficient nor openai compatible sadly 

Related PR: https://github.com/run-llama/llama_index/pull/16666

**Comment by XinyaoWa** [comment]
Hi, this problem has been fixed in PR https://github.com/opea-project/GenAIComps/pull/892

**Comment by joshuayao** [comment]
@logan-markewich Could you please help close the issue if the PR works? Thanks.
