### ISSUE TITLE
[Feature Request] LLM endpoints do not accept chat messages

### ISSUE THREAD

**Issue by logan-markewich** [opea-project/GenAIComps#517]
I noticed the LLM endpoints only accept a single query, but its more common to pass a list of chat message dicts.

For example, if I wanted to implement a chat with docs app with geniai comps, there's actually no proper way to do this.

Many LLM providers support a chat message format (Ollama, vllm, tei) and will automatically apply chat templates to the chat messages for the specific model being used

**Comment by devpramod** [comment]
Hi @logan-markewich Do you mean passing a messages dict like this:

`
curl http://${your_ip}:9000/v1/chat/completions -X POST -d '{
    "model": "Intel/neural-chat-7b-v3-3",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Hello!"
        }
    ],
    "max_new_tokens": 17,
    "top_k": 10,
    "top_p": 0.95,
    "typical_p": 0.95,
    "temperature": 0.01,
    "repetition_penalty": 1.03,
    "streaming": false
}' -H 'Content-Type: application/json'
`

**Comment by logan-markewich** [comment]
@devpramod I was looking at the `LLMParamsDoc` that many llms use as the input object. I don't see a spot for messages? https://github.com/opea-project/GenAIComps/blob/5fb4a38d4e5f68e138411d5168ff574962434439/comps/cores/proto/docarray.py#L133

Am I looking in the wrong spot?

**Comment by devpramod** [comment]
The implementation is in llm.py 
https://github.com/opea-project/GenAIComps/blob/5fb4a38d4e5f68e138411d5168ff574962434439/comps/llms/text-generation/tgi/llm.py#L213

**Comment by logan-markewich** [comment]
Ah ok, so here the input type is specified as a union 
https://github.com/opea-project/GenAIComps/blob/5fb4a38d4e5f68e138411d5168ff574962434439/comps/llms/text-generation/tgi/llm.py#L45

A little confusing, but make sense
