### ISSUE TITLE
comps/version.py version number not updated on main branch

### ISSUE THREAD

**Issue by dbkinder** [opea-project/GenAIComps#524]
I see there's a comps/version.py file that might be the "version number" for the OPEA project.  Here's what it says on the main branch:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

__version__ = "0.8"
```

If this is the project version, it shouldn't say 0.8 on the main branch.  What is the purpose of this version.py file and when is it updated?  I'm using it to get the version number of the project to use in the documentation, but that may be a wrong assumption.

If it is the OPEA project version, the main branch should indicate it's a work in progress version between the last official release (0.8) and the next (0.9) so it might want to say "0.8.99" (meaning it's continued work after the 0.8 release, as done in the Zephyr project)  but should be something other than 0.8 or 0.9, which should be reserved for the official 0.8 and 0.9 releases.

**Comment by dbkinder** [comment]
I now see that the main branch has this version.py file with a value of 1.0.  That's not correct since 1.0 will happen when the branch is tagged with 1.0.

@kding1 @hshen14

**Comment by kevinintel** [comment]
already fixed

**Comment by dbkinder** [comment]
The point is what is this version.py used for and what other parts of OPEA use it?  What's the "version" value on the  main branch between releases?  Do other parts of OPEA use this version.py for their "version"?

**Comment by joshuayao** [comment]
Closed due to no response for over 30 days. Please reopen if the issue persists.
