### ISSUE TITLE
vLLM Openvino Image in not available in docker

### ISSUE THREAD

**Issue by avinashkarani** [opea-project/GenAIComps#552]
Trying to run chatQ&A with vLLM-openVINO and found vllm-openvino is not available as prebuilt image. Also having a helm chat for ChatQ&A with vLLM-openvino as model server will help to run on Xeon with Quantized models.

**Comment by kevinintel** [comment]
If you want to pubish new images, please contact Suyue and abi

**Comment by bharagha** [comment]
Please close this ticket as noted in previous comment.
