### ISSUE TITLE
Embedding Microservice exiting with 404 Issue 

### ISSUE THREAD

**Issue by yogeshmpandey** [opea-project/GenAIComps#585]
Running the following example : 
https://opea-project.github.io/latest/GenAIComps/comps/embeddings/README.html#start-embedding-service-with-tei 

The command mentioned is :

`your_port=8090
model="BAAI/bge-large-en-v1.5"
revision="refs/pr/5"
docker run -p $your_port:80 -v ./data:/data --name tei_server -e http_proxy=$http_proxy -e https_proxy=$https_proxy --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-1.5 --model-id $model --revision $revision`

However, Once we run the command the container is running into this issue.

![image](https://github.com/user-attachments/assets/a348aeb6-ec88-40fc-aa71-8c04defb80e6)

2024-08-30T10:34:45.450812Z  INFO download_artifacts: text_embeddings_backend: backends/src/lib.rs:318: Downloading `onnx/model.onnx`
Error: Could not download model artifacts

Caused by:
    0: request error: HTTP status client error (404 Not Found) for url (https://huggingface.co/BAAI/bge-large-en-v1.5/resolve/refs%2Fpr%2F5/onnx/model.onnx)
    1: HTTP status client error (404 Not Found) for url (https://huggingface.co/BAAI/bge-large-en-v1.5/resolve/refs%2Fpr%2F5/onnx/model.onnx)
    
 Once we remove this _--revision $revision`_ the command works fine.

**Comment by wangkl2** [comment]
@yogeshmpandey The revision for the embedding model has been removed in this commit https://github.com/opea-project/GenAIComps/commit/d60907163e85f2399fbb2fb712e2adefc11fd678 to fix this issue. The github.io page of [TEI embedding service](https://opea-project.github.io/latest/GenAIComps/comps/embeddings/README.html#start-embedding-service-with-tei) also reflects this change. Thanks.
