### ISSUE TITLE
Support Intel Arc GPU

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIComps#629]
#641

**Comment by chen-hu-97** [comment]
With below two commits, it just works on Arc GPU.
https://github.com/chen-hu-97/GenAIComps/commit/81444fc9db67a4ecdb92bd320d811b57d7ce9f1c
https://github.com/chen-hu-97/GenAIExamples/commit/398f34ccfd1217c7484559e12e162d1b2b9b9ae8

A polished version (separated folder for Arc code) is now on private repo.

**Comment by chen-hu-97** [comment]
Please assign this issue to gavinlichn

**Comment by chickenrae** [comment]
gavinlichn does not come up as a user

**Comment by joshuayao** [comment]
Close for PR merged.
