### ISSUE TITLE
Docker image opea/chathistory-mongo-server does not exist on docker hub

### ISSUE THREAD

**Issue by yongfengdu** [opea-project/GenAIComps#718]
In the readme and docker-compose file, it refered to image name: opea/chathistory-mongo-server
https://github.com/opea-project/GenAIComps/tree/main/comps/chathistory/mongo#build-docker-image
https://github.com/opea-project/GenAIComps/blob/main/comps/chathistory/mongo/docker-compose-chathistory-mongo.yaml#L18

However, in the docker hub, there is a docker image named opea/chat-history-service
https://hub.docker.com/r/opea/chat-history-service/tags
Which is also mentioned here:
https://github.com/opea-project/GenAIExamples/blob/main/docker_images_list.md

I think they mean the same one but messed up the name.
Could any one explain or fix this?

**Comment by yongfengdu** [comment]
Similar issue for prompt registry:
opea/prompt-registry-service (https://hub.docker.com/r/opea/prompt-registry-service)
and 
opea/promptregistry-mongo:latest
https://github.com/opea-project/GenAIComps/blob/main/comps/prompt_registry/mongo/docker-compose-prompt-registry-mongo.yaml#L18

**Comment by hteeyeoh** [comment]
We can fix it in the compose yaml to use the image naming and update readme. Need advice and confirmation before proceed. Thank you.

**Comment by yongfengdu** [comment]
The opea/chat-history-service was not updated since a month ago and there is no tag with 1.0. So that might not be the correct one to use.

**Comment by hteeyeoh** [comment]
Ok sure. Need advise from @ashahba  on the actual image name that being published in hub

**Comment by chensuyue** [comment]
Please try again, https://hub.docker.com/r/opea/chathistory-mongo-server/tags

**Comment by chensuyue** [comment]
Not all the images can be upstream directly, we need to pass OSPDT, it takes time.

**Comment by hteeyeoh** [comment]
I have noticed that two image service:
[promptregistry](https://hub.docker.com/r/opea/promptregistry-mongo-server)
[chathistroy](https://hub.docker.com/r/opea/chathistory-mongo-server/tags)
