### ISSUE TITLE
Create Issue Templates for the GenAIComps Repo

### ISSUE THREAD

**Issue by kdruckman** [opea-project/GenAIComps#748]
The opea-project/GenAIExamples repo has issue templates in place for bug reports and feature requests. Similar templates would be helpful here as well. 

GitHub documentation on how to do this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by isaacncz** [comment]
@NeoZhangJianyu PR has been approved and merged, please proceed to close ticket

**Comment by chensuyue** [comment]
@isaacncz seems the template has some issue, https://github.com/opea-project/GenAIComps/blob/main/.github/ISSUE_TEMPLATE/1_bug_template.yml 
![image](https://github.com/user-attachments/assets/d5c0279c-3239-4d75-ba14-d7c8717f5e63)
No bug type to choose, 
![image](https://github.com/user-attachments/assets/7f80be66-206a-4dcf-bbba-37b4b105e578)

**Comment by isaacncz** [comment]
@chensuyue fixed the issue. Attachment have to be uploaded through textarea. 
![image](https://github.com/user-attachments/assets/4e663684-e1fc-4531-8160-6ee5f0f1c7eb)
