### ISSUE TITLE
Pinecone service fails to start

### ISSUE THREAD

**Issue by dcmiddle** [opea-project/GenAIComps#809]
# Background:
I don't think the pinecone service can start as scripted in the CI tests.
I had to revert some simple changes in a PR because pinecone could not pass CI. (https://github.com/opea-project/GenAIComps/pull/762/commits/ba2bf103bb7fc6f1b59f7dee5adb49d0aa113919)

I think @lvliang-intel may have also reverted valid changes recently because of the same CI failure (but I'm not certain).
( https://github.com/opea-project/GenAIComps/pull/763/commits/d5533a8374e3189bb19a2ce4bd6287657666b41d )

# Simple Reproducer

See: https://github.com/opea-project/GenAIComps/pull/810
The only change is setting a timeout in the test from 2m to 120s. This just forces CI to run this test.

The service fails to start:
https://github.com/opea-project/GenAIComps/blob/main/tests/retrievers/test_retrievers_pinecone_langchain.sh#L36
```    docker run -d --name="test-comps-retriever-pinecone-server" -p ${retriever_port}:7000 --ipc=host -e HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN} -e TEI_EMBEDDING_ENDPOINT=$TEI_EMBEDDING_ENDPOINT -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e PINECONE_API_KEY=$PINECONE_API_KEY -e PINECONE_INDEX_NAME=$PINECONE_INDEX_NAME -e INDEX_NAME=$PINECONE_INDEX_NAME opea/retriever-pinecone:comps```

https://github.com/opea-project/GenAIComps/blob/main/comps/retrievers/pinecone/langchain/retriever_pinecone.py#L92
```vector_db = PineconeVectorStore(embedding=embeddings, index_name=PINECONE_INDEX_NAME)```

### Stack trace:
https://github.com/opea-project/GenAIComps/actions/runs/11446117010/job/31844626243?pr=810#step:4:942

# More Convoluted Reproducer

This reproducer https://github.com/opea-project/GenAIComps/pull/767 replaces a deprecated API and updates the test with a better timeout mechanism.

Fails in the same place as above:
https://github.com/opea-project/GenAIComps/actions/runs/11444738367/job/31840299594?pr=767#step:4:879

https://github.com/opea-project/GenAIComps/blob/main/comps/retrievers/pinecone/langchain/retriever_pinecone.py#L92
```vector_db = PineconeVectorStore(embedding=embeddings, index_name=PINECONE_INDEX_NAME)```

### Stack trace:
https://github.com/opea-project/GenAIComps/actions/runs/11444738367/job/31840299594?pr=767#step:4:917

**Comment by lvliang-intel** [comment]
It's fixed by PR #816
