### ISSUE TITLE
gpt-sovits: not runnable in K8S restricted pod security standards

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIComps#838]
The current gpt-sovits container requires to run as root within the container, which prevents it to be runnable by [K8S restricted pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

We need to make it runnable in that configuration by make it run as a normal user, not root within the container, just like other opea GenAIComps containers.

**Comment by lianhao** [comment]
I've submitted the PR #839 to address this.

**Comment by srinarayan-srikanthan** [comment]
closing as PR merged.
