### ISSUE TITLE
DataPrep Component | Qdrant | ingest_documents(doc_path: DocPath)

### ISSUE THREAD

**Issue by sachop0974** [opea-project/GenAIComps#92]
The following should support passing "http://path-to-pdf" to test the service; By default the function looks for file name in the local container.

curl -X POST -H "Content-Type: application/json" -d '{"path":"/path/to/document"}' http://localhost:6000/v1/dataprep

[[
ingest_documents(doc_path: DocPath)
docment_loader(doc_path)
fitz.open(file_path)
]]

**Comment by xiguiw** [comment]
@sachop0974 
Yes, you are right. 
Thank you for your feedback.
It supports to pass remote link file to test the service.

Please refer to  https://github.com/xiguiw/GenAIExamples/blob/doc-update/ChatQnA/docker/gaudi/README.md

![image](https://github.com/opea-project/GenAIComps/assets/111278656/2188fa65-7ecc-4687-9dbf-829b9320f6c3)

**Comment by yinghu5** [comment]
Hi  we close the issue. please feel free to reopen it if any problem
