### ISSUE TITLE
[bug] embedding microservice almost openai compatible but not fully

### ISSUE THREAD

**Issue by rbrugaro** [opea-project/GenAIComps#926]
We claim OPENAI compatible but OPEA still returns some objects as null that should be populated.
OPEA TEI: "usage":null, "model":null,
Bare TEI: "model":"BAAI/bge-large-en-v1.5","usage":{"prompt_tokens":12,"total_tokens":12}

This issue of milling objects applies to other microservices too. Might be good to systematically correct for all.

**Comment by logan-markewich** [comment]
I think https://github.com/run-llama/llama_index/pull/16666 is also blocked by this. You cannot send a list of texts to an embedding endpoint

**Comment by rbrugaro** [comment]
@logan-markewich  I retested https://github.com/run-llama/llama_index/pull/16666 and is working with list of text input. It was fixed on PR: https://github.com/opea-project/GenAIComps/pull/892
I think the only piece missing for full openai compatibility are the usage and model values.

**Comment by lkk12014402** [comment]
> @logan-markewich I retested [run-llama/llama_index#16666](https://github.com/run-llama/llama_index/pull/16666) and is working with list of text input. It was fixed on PR: #892 I think the only piece missing for full openai compatibility are the usage and model values.

hi, we follow this doc https://platform.openai.com/docs/api-reference/embeddings to define the input/output format https://github.com/opea-project/GenAIComps/blob/main/comps/cores/proto/api_protocol.py#L83C1-L107C1. It's true that some values ​​are null because we don't need them.

**Comment by rbrugaro** [comment]
@lkk12014402 , by "we don't need them" you mean OPEA reference examples don't make use of those values at the moment? since we are integrating OPEA microservices in llama-index, and llama-index users expect openai compatible for diverse use cases and to easily swap with other cloud/prem alternatives in their deployments it would still be good to address the gaps.

**Comment by ftian1** [comment]
Rita and Logan's concern are valid, we will fix it asap. @lkk12014402 @logan-markewich @rbrugaro

**Comment by lkk12014402** [comment]
> @lkk12014402 , by "we don't need them" you mean OPEA reference examples don't make use of those values at the moment? since we are integrating OPEA microservices in llama-index, and llama-index users expect openai compatible for diverse use cases and to easily swap with other cloud/prem alternatives in their deployments it would still be good to address the gaps.

hi, @rbrugaro  sorry, we use the wrong tei endpoint `/embed`, with which we can't get the informations of `model` and `usage`. And I will fix it by using `/v1/embeddings`

**Comment by lkk12014402** [comment]
> We claim OPENAI compatible but OPEA still returns some objects as null that should be populated. OPEA TEI: "usage":null, "model":null, Bare TEI: "model":"BAAI/bge-large-en-v1.5","usage":{"prompt_tokens":12,"total_tokens":12}
> 
> This issue of milling objects applies to other microservices too. Might be good to systematically correct for all.

hi, @rbrugaro I fix the issue with this pr https://github.com/opea-project/GenAIComps/pull/1035

**Comment by ftian1** [comment]
@logan-markewich FYI. pls be aware of this fix made by Kaokao.
