### ISSUE TITLE
[Bug] dataprep test run fail on Xeon

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#931]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### Description

dataprep/test_dataprep_multimodal_redis_langchain.sh and dataprep/test_dataprep_multimedia.sh test fail. 
log link: 
dataprep/test_dataprep_multimodal_redis_langchain.sh: https://github.com/opea-project/GenAIComps/actions/runs/11929971908/job/33250378694
dataprep/test_dataprep_multimedia.sh:  https://github.com/opea-project/GenAIComps/actions/runs/11929971908/job/33250379480
In addition, test_dataprep_multimedia.sh  has port conflicts (9099). The DOCKER_NAME name in validate_microservices() is inconsistent before and after.
After modifying 9099 to 5045 and correcting DOCKER-NAME, the local test log error is consistent with test_dataprep_multimodal_redis_langchain.sh.
![image](https://github.com/user-attachments/assets/385eaa8b-b920-4c26-909a-f320f33247bc)

**Comment by MSCetin37** [comment]
moviepy 2.0.0 is released at Nov 19, 2024. I will fix the issue.

**Comment by tileintel** [comment]
I have checked the previous release. It is `moviepy==1.0.3`. Would you like to fix the source code to adapt the latest released moviepy library? Or would you like to update the docker file to install the correct version `moviepy==1.0.3`? Please let me know.

**Comment by MSCetin37** [comment]
@tileintel, we are working on it.

**Comment by ZePan110** [comment]
@tileintel @MSCetin37  Thank you for your reply. I added some comments in the PR

**Comment by ZePan110** [comment]
This issue is fixed by https://github.com/opea-project/GenAIComps/pull/942
CD test pass, log link: https://github.com/opea-project/GenAIComps/actions/runs/12002252809
So close this issue.
