### ISSUE TITLE
[Bug] reranks_fastrag run fail on Xeon

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#932]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### Description

reranks/test_reranks_fastrag.sh test fail.
RuntimeError: The embedding model has not been loaded. Please call warm_up() before running.
Log link: https://github.com/opea-project/GenAIComps/actions/runs/11929971908/job/33251991739

**Comment by ZePan110** [comment]
@gadmarkovits  could you please take a look at this issue?

**Comment by gadmarkovits** [comment]
This is due to compatibility issues between fastrag and the new version of haystack. I submitted a pr to fastrag that should solve this. One the pr is merged, a new version of fastrag will be released and the test should pass. I will update here once the new fastrag version is released.

**Comment by ZePan110** [comment]
CD test pass, log link: https://github.com/opea-project/GenAIComps/actions/runs/12021448485/job/33513183674
So close this issue.
