### ISSUE TITLE
[Bug] vectorstores test fail on Xeon

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#933]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### Description

./vectorstores/test_vectorstores_pathway.sh test fail 
Log link: https://github.com/opea-project/GenAIComps/actions/runs/11929971908/job/33252617113

**Comment by chensuyue** [comment]
@berkecanrizai

**Comment by ZePan110** [comment]
This issue is fixed by https://github.com/opea-project/GenAIComps/pull/940
CD test pass, log link:  https://github.com/opea-project/GenAIComps/actions/runs/11965487915/job/33364062380
So close this issue.
