### ISSUE TITLE
[Bug]retrievers_pathway test fail on Xeon

### ISSUE THREAD

**Issue by ZePan110** [opea-project/GenAIComps#934]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### Description

./retrievers/test_retrievers_pathway_langchain.sh test fail on Xeon
Log link: https://github.com/opea-project/GenAIComps/actions/runs/11929971908/job/33252617113
![image](https://github.com/user-attachments/assets/16272ffd-c895-4bb6-899b-875791ee243d)

**Comment by berkecanrizai** [comment]
Hi @ZePan110 , could you check this: https://github.com/opea-project/GenAIComps/pull/940

**Comment by ZePan110** [comment]
> Hi @ZePan110 , could you check this: #940

Thank for your fix PR

**Comment by ZePan110** [comment]
> Hey @ZePan110 is the error still there?
> 
> I saw this snippet in the above logs:
> 
> ```
> Unable to find image 'opea/vectorstore-pathway:comps' locally
> docker: Error response from daemon: manifest for opea/vectorstore-pathway:comps not found: manifest unknown: manifest unknown.
> ```
> 
> was there some change in the tag names or builds? From the logs, it seems like the vectorstore image was built successfully.

Let me test again

**Comment by ZePan110** [comment]
The previous CD failure was due to a path issue in the test script, which was fixed and the CI test passed. https://github.com/opea-project/GenAIComps/actions/runs/12021612130/job/33512416427?pr=946
This issue is fixed by https://github.com/opea-project/GenAIComps/pull/940
So we can close this issue
