### ISSUE TITLE
[Bug] speecht5-gaudi image failed to launch

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIComps#948]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Gaudi2

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [ ] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

git commit id: c5b8cdd

### Description

PR #929 breaks the speecht5-gaudi image with the following error. The lacks of CI test for image speecht5-gaudi makes the error merged in without any notice, the CI currently only tests the speecht5 image on Xeon environment.

```
Traceback (most recent call last):
  File "/home/user/comps/tts/speecht5/dependency/speecht5_server.py", line 15, in <module>
    from comps import CustomLogger
  File "/home/user/comps/__init__.py", line 7, in <module>
    from comps.cores.proto.docarray import (
  File "/home/user/comps/cores/proto/docarray.py", line 10, in <module>
    from pydantic import Field, conint, conlist, field_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
```

### Reproduce steps

1. build the docker image locally:
```
sudo docker build -t speecht5-gaudi:test --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f comps/tts/speecht5/dependency/Dockerfile.intel_hpu .
```

2. launch the just built docker image:
```
sudo docker run -p 7055:7055 --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --ipc=host -e http_proxy=$http_proxy -e https_proxy=$https_proxy  speecht5-gaudi:test
```

**Comment by Spycsh** [comment]
https://github.com/opea-project/GenAIComps/pull/949 fixed this.

**Comment by lianhao** [comment]
Close this since both fixing and CI test has been added
